[env:nodemcuv2]
platform = espressif8266
framework = arduino
board = esp01
upload_protocol = esptool
upload_speed = 921600
lib_deps =
    links2004/WebSockets
    arduino-libraries/Arduino_JSON

; Set CPU to 160MHz
board_build.f_cpu = 160000000L

; 4MB flash size and reserve 1MB for filesystem
board_build.flash_size = 4MB
board_build.ldscript = eagle.flash.4m1m.ld
; board_build.ldscript = eagle.flash.4m512.ld ; 3.5MB Code 512KB Filesystem

; Set filesystem to LittleFS
board_build.filesystem = littlefs

build_flags =
    -D WIFI_SSID=\"${sysenv.WIFI_SSID}\"
    -D WIFI_PASSWD=\"${sysenv.WIFI_PASSWD}\"
